apiVersion: v1
kind: Service
metadata:
  name: google-home-streamer-service
spec:
  selector:
    app: google-home-streamer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
